# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://andrecarvalho.org" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: andre carvalho
  avatar:
  gravatar: bc403142cbfb5a37fa8ca92b2f6730cb
  description: "andre carvalho's personal website. concatenações de chico: fico aqui inventando moda" # used by search engines

  # Header and footer text
  header_text: # nada for now
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a>
   with <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  flickr:
  github: alcarvalho
  google_plus:
  linkedin: https://br.linkedin.com/in/alcarv # Full URL
  pinterest:
  reddit:
  soundcloud: andre-carvalho
  stack_exchange: http://stackoverflow.com/users/2317346/andre-luiz # Full URL
  steam:
  tumblr:
  bluesky: aloak
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-61304837-1
  disqus_shortname: alcarvalho
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_all: "All"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
